CREATE TABLE "mytable" (
  "-- ============================================" text
);

INSERT INTO "mytable" ("-- ============================================")
VALUES
('-- SIP MANAGEMENT SYSTEM DATABASE SCHEMA'),
('-- PostgreSQL'),
('-- ============================================'),
('DROP TABLE IF EXISTS audit_logs CASCADE;'),
('DROP TABLE IF EXISTS notifications CASCADE;'),
('DROP TABLE IF EXISTS compliance_alerts CASCADE;'),
('DROP TABLE IF EXISTS compliance_checks CASCADE;'),
('DROP TABLE IF EXISTS sip_schedules CASCADE;'),
('DROP TABLE IF EXISTS transactions CASCADE;'),
('DROP TABLE IF EXISTS investments CASCADE;'),
('DROP TABLE IF EXISTS system_users CASCADE;'),
('DROP TABLE IF EXISTS funds CASCADE;'),
('DROP TABLE IF EXISTS users CASCADE;'),
('-- ============================================'),
('-- USERS'),
('-- ============================================'),
('CREATE TABLE users ('),
('user_id SERIAL PRIMARY KEY'),
('full_name VARCHAR(120) NOT NULL'),
('email VARCHAR(120) UNIQUE NOT NULL'),
('phone VARCHAR(15) UNIQUE'),
('pan_number VARCHAR(10) UNIQUE'),
('aadhaar_last4 CHAR(4)'),
('role VARCHAR(30) NOT NULL'),
('mfa_enabled BOOLEAN DEFAULT FALSE'),
('kyc_status VARCHAR(20)'),
('city VARCHAR(50)'),
('state VARCHAR(50)'),
('created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
('last_login TIMESTAMP'),
('status VARCHAR(20) DEFAULT ''ACTIVE'''),
(');'),
('-- ============================================'),
('-- FUNDS'),
('-- ============================================'),
('CREATE TABLE funds ('),
('fund_id SERIAL PRIMARY KEY'),
('fund_code VARCHAR(20) UNIQUE NOT NULL'),
('scheme_name VARCHAR(150) NOT NULL'),
('fund_house VARCHAR(100)'),
('category VARCHAR(50)'),
('risk_level VARCHAR(30)'),
('nav NUMERIC(10'),
('aum BIGINT'),
('expense_ratio NUMERIC(5'),
('benchmark VARCHAR(100)'),
('exit_load NUMERIC(4'),
('launch_date DATE'),
(');'),
('-- ============================================'),
('-- SYSTEM USERS'),
('-- ============================================'),
('CREATE TABLE system_users ('),
('system_user_id SERIAL PRIMARY KEY'),
('name VARCHAR(120)'),
('email VARCHAR(120) UNIQUE'),
('role VARCHAR(40)'),
('department VARCHAR(50)'),
('status VARCHAR(20)'),
('last_login TIMESTAMP'),
(');'),
('-- ============================================'),
('-- INVESTMENTS'),
('-- ============================================'),
('CREATE TABLE investments ('),
('investment_id SERIAL PRIMARY KEY'),
('user_id INT NOT NULL'),
('fund_id INT NOT NULL'),
('investment_type VARCHAR(20)'),
('sip_amount NUMERIC(12'),
('lumpsum_amount NUMERIC(12'),
('units NUMERIC(15'),
('purchase_nav NUMERIC(10'),
('current_nav NUMERIC(10'),
('current_value NUMERIC(15'),
('returns_percent NUMERIC(8'),
('status VARCHAR(20)'),
('created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
('CONSTRAINT fk_investment_user'),
('FOREIGN KEY(user_id)'),
('REFERENCES users(user_id)'),
('CONSTRAINT fk_investment_fund'),
('FOREIGN KEY(fund_id)'),
('REFERENCES funds(fund_id)'),
(');'),
('-- ============================================'),
('-- TRANSACTIONS'),
('-- ============================================'),
('CREATE TABLE transactions ('),
('transaction_id SERIAL PRIMARY KEY'),
('investment_id INT NOT NULL'),
('user_id INT NOT NULL'),
('fund_id INT NOT NULL'),
('transaction_type VARCHAR(30)'),
('amount NUMERIC(12'),
('units NUMERIC(15'),
('nav NUMERIC(10'),
('stamp_duty NUMERIC(10'),
('exit_load NUMERIC(10'),
('settlement_date DATE'),
('status VARCHAR(30)'),
('created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
('CONSTRAINT fk_transaction_investment'),
('FOREIGN KEY(investment_id)'),
('REFERENCES investments(investment_id)'),
('CONSTRAINT fk_transaction_user'),
('FOREIGN KEY(user_id)'),
('REFERENCES users(user_id)'),
('CONSTRAINT fk_transaction_fund'),
('FOREIGN KEY(fund_id)'),
('REFERENCES funds(fund_id)'),
(');'),
('-- ============================================'),
('-- SIP SCHEDULES'),
('-- ============================================'),
('CREATE TABLE sip_schedules ('),
('schedule_id SERIAL PRIMARY KEY'),
('user_id INT NOT NULL'),
('fund_id INT NOT NULL'),
('sip_amount NUMERIC(12'),
('frequency VARCHAR(20)'),
('debit_day INT'),
('next_debit DATE'),
('bank_account VARCHAR(30)'),
('status VARCHAR(20)'),
('CONSTRAINT fk_schedule_user'),
('FOREIGN KEY(user_id)'),
('REFERENCES users(user_id)'),
('CONSTRAINT fk_schedule_fund'),
('FOREIGN KEY(fund_id)'),
('REFERENCES funds(fund_id)'),
(');'),
('-- ============================================'),
('-- COMPLIANCE CHECKS'),
('-- ============================================'),
('CREATE TABLE compliance_checks ('),
('check_id SERIAL PRIMARY KEY'),
('user_id INT NOT NULL'),
('risk_score INT'),
('aml_status VARCHAR(20)'),
('pep_check BOOLEAN'),
('sanction_check BOOLEAN'),
('result VARCHAR(30)'),
('remarks TEXT'),
('checked_at TIMESTAMP'),
('CONSTRAINT fk_check_user'),
('FOREIGN KEY(user_id)'),
('REFERENCES users(user_id)'),
(');'),
('-- ============================================'),
('-- COMPLIANCE ALERTS'),
('-- ============================================'),
('CREATE TABLE compliance_alerts ('),
('alert_id SERIAL PRIMARY KEY'),
('check_id INT NOT NULL'),
('severity VARCHAR(20)'),
('status VARCHAR(30)'),
('assigned_to INT'),
('opened_at TIMESTAMP'),
('resolved_at TIMESTAMP'),
('resolution_notes TEXT'),
('CONSTRAINT fk_alert_check'),
('FOREIGN KEY(check_id)'),
('REFERENCES compliance_checks(check_id)'),
('CONSTRAINT fk_alert_officer'),
('FOREIGN KEY(assigned_to)'),
('REFERENCES system_users(system_user_id)'),
(');'),
('-- ============================================'),
('-- NOTIFICATIONS'),
('-- ============================================'),
('CREATE TABLE notifications ('),
('notification_id SERIAL PRIMARY KEY'),
('user_id INT NOT NULL'),
('channel VARCHAR(20)'),
('title VARCHAR(150)'),
('message TEXT'),
('read_status BOOLEAN'),
('sent_at TIMESTAMP'),
('CONSTRAINT fk_notification_user'),
('FOREIGN KEY(user_id)'),
('REFERENCES users(user_id)'),
(');'),
('-- ============================================'),
('-- AUDIT LOGS'),
('-- ============================================'),
('CREATE TABLE audit_logs ('),
('log_id SERIAL PRIMARY KEY'),
('actor_id INT NOT NULL'),
('actor_role VARCHAR(40)'),
('action VARCHAR(100)'),
('table_name VARCHAR(50)'),
('record_id INT'),
('ip_address VARCHAR(45)'),
('session_id VARCHAR(100)'),
('log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
('CONSTRAINT fk_audit_user'),
('FOREIGN KEY(actor_id)'),
('REFERENCES system_users(system_user_id)'),
(');'),
('-- ============================================'),
('-- INDEXES'),
('-- ============================================'),
('CREATE INDEX idx_users_email'),
('ON users(email);'),
('CREATE INDEX idx_users_pan'),
('ON users(pan_number);'),
('CREATE INDEX idx_funds_code'),
('ON funds(fund_code);'),
('CREATE INDEX idx_investments_user'),
('ON investments(user_id);'),
('CREATE INDEX idx_transactions_user'),
('ON transactions(user_id);'),
('CREATE INDEX idx_transactions_investment'),
('ON transactions(investment_id);'),
('CREATE INDEX idx_sip_user'),
('ON sip_schedules(user_id);'),
('CREATE INDEX idx_compliance_user'),
('ON compliance_checks(user_id);'),
('CREATE INDEX idx_notification_user'),
('ON notifications(user_id);'),
('CREATE INDEX idx_audit_actor'),
('ON audit_logs(actor_id);'),
('-- ============================================'),
('-- END OF SCHEMA'),
('-- ============================================');
